apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: squ1fn8l4-dotnet-basic
  janus-idp.io/tekton: squ1fn8l4-dotnet-basic
  backstage.io/kubernetes-id: squ1fn8l4-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: squ1fn8l4-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
